### ISSUE TITLE
cv2.findContours function error on python 3.7

### ISSUE THREAD

**Issue by rayavarapuvikram1** [arshdefoamed/hand-gesture-recognition-using-opencv#1]
File "e:/All Programs/PythonProjects/test.py", line 133, in <module>
    contouredPic,contoursVec, hierarchy = cv2.findContours(morphedFrame.copy(),cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by rayavarapuvikram1** [comment]
Got solution from docs

**Comment by raratul** [comment]
What's the solution?

**Comment by rayavarapuvikram1** [comment]
line 144 in [link](https://github.com/rayavarapuvikram1/hand-gesture-recognition-using-opencv/blob/fc9f4a805e456c7ffb93f5f26410b80c15b82f4e/faceRecognition.py#L144)
